# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(923, 681)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(243, 663))
        self.frame.setMaximumSize(QtCore.QSize(243, 663))
        self.frame.setObjectName("frame")
        self.frame1 = QtWidgets.QFrame(self.frame)
        self.frame1.setGeometry(QtCore.QRect(0, 0, 243, 331))
        self.frame1.setMinimumSize(QtCore.QSize(243, 331))
        self.frame1.setMaximumSize(QtCore.QSize(243, 331))
        self.frame1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame1.setObjectName("frame1")
        self.lblCapCam = QtWidgets.QLabel(self.frame1)
        self.lblCapCam.setGeometry(QtCore.QRect(10, 10, 223, 311))
        self.lblCapCam.setMinimumSize(QtCore.QSize(223, 311))
        self.lblCapCam.setMaximumSize(QtCore.QSize(223, 311))
        self.lblCapCam.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lblCapCam.setText("")
        self.lblCapCam.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCapCam.setObjectName("lblCapCam")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 330, 243, 331))
        self.frame_2.setMinimumSize(QtCore.QSize(243, 331))
        self.frame_2.setMaximumSize(QtCore.QSize(243, 331))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setObjectName("frame_2")
        self.lblCapCard = QtWidgets.QLabel(self.frame_2)
        self.lblCapCard.setGeometry(QtCore.QRect(10, 10, 223, 311))
        self.lblCapCard.setMinimumSize(QtCore.QSize(223, 311))
        self.lblCapCard.setMaximumSize(QtCore.QSize(223, 311))
        self.lblCapCard.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lblCapCard.setText("")
        self.lblCapCard.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCapCard.setObjectName("lblCapCard")
        self.horizontalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_21 = QtWidgets.QFrame(self.centralwidget)
        self.frame_21.setMinimumSize(QtCore.QSize(575, 663))
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lyTableCards = QtWidgets.QVBoxLayout()
        self.lyTableCards.setObjectName("lyTableCards")
        self.verticalLayout.addLayout(self.lyTableCards)
        self.frame_3 = QtWidgets.QFrame(self.frame_21)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 180))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 180))
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_5 = QtWidgets.QWidget(self.groupBox_4)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setMinimumSize(QtCore.QSize(65, 0))
        self.label.setMaximumSize(QtCore.QSize(65, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.cmbSets = QtWidgets.QComboBox(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.cmbSets.setFont(font)
        self.cmbSets.setObjectName("cmbSets")
        self.horizontalLayout_4.addWidget(self.cmbSets)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setMinimumSize(QtCore.QSize(0, 20))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.sboxSegs = QtWidgets.QSpinBox(self.widget)
        self.sboxSegs.setAlignment(QtCore.Qt.AlignCenter)
        self.sboxSegs.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sboxSegs.setMinimum(6)
        self.sboxSegs.setMaximum(99)
        self.sboxSegs.setProperty("value", 13)
        self.sboxSegs.setObjectName("sboxSegs")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.sboxSegs)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget1 = QtWidgets.QWidget(self.groupBox_4)
        self.widget1.setObjectName("widget1")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget1)
        self.formLayout_3.setContentsMargins(1, 1, -1, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.sboxCapAcc = QtWidgets.QSpinBox(self.widget1)
        self.sboxCapAcc.setAlignment(QtCore.Qt.AlignCenter)
        self.sboxCapAcc.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.sboxCapAcc.setMinimum(400)
        self.sboxCapAcc.setMaximum(4000)
        self.sboxCapAcc.setProperty("value", 3000)
        self.sboxCapAcc.setObjectName("sboxCapAcc")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sboxCapAcc)
        self.verticalLayout_2.addWidget(self.widget1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.groupBox_4, 0, QtCore.Qt.AlignTop)
        self.gpbox_Cardmarket = QtWidgets.QGroupBox(self.frame_3)
        self.gpbox_Cardmarket.setMinimumSize(QtCore.QSize(0, 0))
        self.gpbox_Cardmarket.setObjectName("gpbox_Cardmarket")
        self.widget_2 = QtWidgets.QWidget(self.gpbox_Cardmarket)
        self.widget_2.setGeometry(QtCore.QRect(10, 20, 120, 150))
        self.widget_2.setMinimumSize(QtCore.QSize(120, 150))
        self.widget_2.setMaximumSize(QtCore.QSize(120, 150))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnSendToCardmarket = QtWidgets.QPushButton(self.widget_2)
        self.btnSendToCardmarket.setMinimumSize(QtCore.QSize(0, 40))
        self.btnSendToCardmarket.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btnSendToCardmarket.setObjectName("btnSendToCardmarket")
        self.verticalLayout_3.addWidget(self.btnSendToCardmarket)
        self.btnDelSelectedRows = QtWidgets.QPushButton(self.widget_2)
        self.btnDelSelectedRows.setMinimumSize(QtCore.QSize(0, 40))
        self.btnDelSelectedRows.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btnDelSelectedRows.setObjectName("btnDelSelectedRows")
        self.verticalLayout_3.addWidget(self.btnDelSelectedRows)
        self.btnDelAllCards = QtWidgets.QPushButton(self.widget_2)
        self.btnDelAllCards.setMinimumSize(QtCore.QSize(0, 40))
        self.btnDelAllCards.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btnDelAllCards.setObjectName("btnDelAllCards")
        self.verticalLayout_3.addWidget(self.btnDelAllCards)
        self.horizontalLayout_3.addWidget(self.gpbox_Cardmarket)
        self.verticalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignBottom)
        self.frame_4 = QtWidgets.QFrame(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnInit = QtWidgets.QPushButton(self.frame_4)
        self.btnInit.setMinimumSize(QtCore.QSize(85, 85))
        self.btnInit.setMaximumSize(QtCore.QSize(85, 85))
        self.btnInit.setObjectName("btnInit")
        self.horizontalLayout_2.addWidget(self.btnInit, 0, QtCore.Qt.AlignLeft)
        self.lcdTimer = QtWidgets.QLCDNumber(self.frame_4)
        self.lcdTimer.setMinimumSize(QtCore.QSize(85, 85))
        self.lcdTimer.setMaximumSize(QtCore.QSize(85, 85))
        self.lcdTimer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdTimer.setLineWidth(0)
        self.lcdTimer.setSmallDecimalPoint(False)
        self.lcdTimer.setDigitCount(2)
        self.lcdTimer.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdTimer.setProperty("value", 0.0)
        self.lcdTimer.setObjectName("lcdTimer")
        self.horizontalLayout_2.addWidget(self.lcdTimer)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnConfig = QtWidgets.QPushButton(self.frame_4)
        self.btnConfig.setMinimumSize(QtCore.QSize(85, 85))
        self.btnConfig.setMaximumSize(QtCore.QSize(85, 85))
        self.btnConfig.setObjectName("btnConfig")
        self.horizontalLayout_2.addWidget(self.btnConfig, 0, QtCore.Qt.AlignRight)
        self.btnExit = QtWidgets.QPushButton(self.frame_4)
        self.btnExit.setMinimumSize(QtCore.QSize(85, 85))
        self.btnExit.setMaximumSize(QtCore.QSize(85, 85))
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_2.addWidget(self.btnExit)
        self.verticalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.frame_21)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Escama"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Opciones"))
        self.label.setText(_translate("MainWindow", "Expansión:"))
        self.label_2.setText(_translate("MainWindow", "Tiempo de captura:"))
        self.label_3.setText(_translate("MainWindow", "Segundos"))
        self.label_4.setText(_translate("MainWindow", "Precisión de captura:"))
        self.gpbox_Cardmarket.setTitle(_translate("MainWindow", "Cardmarket"))
        self.btnSendToCardmarket.setText(_translate("MainWindow", "VENDER"))
        self.btnDelSelectedRows.setText(_translate("MainWindow", "BORRAR\n"
"SELECIONADOS"))
        self.btnDelAllCards.setText(_translate("MainWindow", "BORRAR\n"
"TODAS"))
        self.btnInit.setText(_translate("MainWindow", "INICIAR"))
        self.btnConfig.setText(_translate("MainWindow", "CONF.\n"
"ESCAMA"))
        self.btnExit.setText(_translate("MainWindow", "SALIR"))


